version: '3'
services:
  python-demo:
    image: python-demo:latest
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: python-code
    volumes:
      - .:/demo
    ports:
      - 9090:9090
    command: python app.py
  python-demo2:
    image: python-demo2:latest
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: python-code2
    volumes:
      - .:/demo2
    ports:
      - 9100:9100
    command: python app2.py
