version: '3'
services:
  python-demo:
    image: python-demo:latest
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: python-code
    volumes:
      - .:/demo
    ports:
      - 9090:9090
    command: python3 app.py
  python-demo2:
    image: python-demo2:latest
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: python-code2
    volumes:
      - .:/demo2
    ports:
      - 9100:9100
    command: python3 app2.py
  python-demo3:
    image: python-demo3:latest
    build:
      context: .
      dockerfile: Dockerfile3
    container_name: python-code3
    volumes:
      - .:/demo3
    ports:
      - 9110:9110
    command: python3 app3.py
