version: '3'
services:
  python-demo:
    image: python-demo:latest
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: python-code
    volumes:
      - .:/demo
    command: python3 app.py
  python-demo2:
    image: python-demo2:latest
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: python-code2
    volumes:
      - .:/demo2
    command: python3 app2.py
